server:
  port: 8067

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pwms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

mybatis:
  mapper-locations: classpath:com/weblogb/pwms/mapper/*Mapper.xml